# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StructureTheChaos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StructureTheChaos

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'RxCocoa'
  pod 'RxSwift'

  target 'StructureTheChaosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StructureTheChaosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
